Issue#120: add logger to controller golang componennnt
kappnav/controller pull request #35
Opened 2020-03-02 19:37 UTC by amylin1

for issue#120

2020-03-10 19:29 UTC, paulben commented
Amy, Looks good. A couple comments:

I need to be able to specify log levels on the go test command, for example to run with log level 5:

`go test -v --args -v 5`
`go test -run TestAddResource -v --args -v 5`

This was very useful to me on a number of occasions.

Also please run the command `goreturns -w .` on the source, which will format it to golang standard conventions. It's a standard practice in the go world to format code consistently, I do it on all the code I've done. I can show you how to setup vscode to do it automatically as you code if you would like.

2020-03-10 20:46 UTC, paulben requested changes
Amy, see my comments above.

2020-03-17 18:53 UTC, amylin1 commented
I added -loglevel <none|warning|error|info|debug|entry|all> for unit test, i.e.
go test -v --arg -loglevel debug
will enable debug log level in all unit test.

I also run "goreturns -w" to reformat all go programs under controller.

2020-03-27 13:39 UTC, paulben approved these changes

2020-03-27 17:52 UTC, merged